/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_B0_12 (coord K14), TX */
/* Routed pin properties */
#define BOARD_INITPINS_TX_PERIPHERAL                                     LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_TX_SIGNAL                                              TX   /*!< Signal name */

/* GPIO_AD_B0_13 (coord L14), RX */
/* Routed pin properties */
#define BOARD_INITPINS_RX_PERIPHERAL                                     LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_RX_SIGNAL                                              RX   /*!< Signal name */

/* GPIO_AD_B0_09 (coord F14), LED_F14 */
/* Routed pin properties */
#define BOARD_INITPINS_LED_F14_PERIPHERAL                                  GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_LED_F14_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LED_F14_CHANNEL                                        9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_F14_GPIO                                        GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_F14_GPIO_PIN                                       9U   /*!< GPIO pin number */
#define BOARD_INITPINS_LED_F14_GPIO_PIN_MASK                          (1U << 9U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LED_F14_PORT                                        GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LED_F14_PIN                                            9U   /*!< PORT pin number */
#define BOARD_INITPINS_LED_F14_PIN_MASK                               (1U << 9U)   /*!< PORT pin mask */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
